 CREATE TABLE IF NOT EXISTS Drivers  (
            driverId INTEGER,
            driverRef VARCHAR,
            number VARCHAR,
            code VARCHAR,
            forename VARCHAR,
            surname VARCHAR,
            dob VARCHAR,
            nationality VARCHAR,
            url VARCHAR;

CREATE TABLE IF NOT EXISTS Races (
            raceId INTEGER,
            year INTEGER,
            round INTEGER,
            circuitId INTEGER,
            name VARCHAR,
            date DATE,
            time VARCHAR,
            url VARCHAR,
            fp1_date VARCHAR,
            fp1_time VARCHAR,
            fp2_date VARCHAR,
            fp2_time VARCHAR,
            fp3_date VARCHAR,
            fp3_time VARCHAR,
            quali_date VARCHAR,
            quali_time VARCHAR,
            sprint_date VARCHAR,
            sprint_time VARCHAR;

CREATE TABLE IF NOT EXISTS Results  (
            resultId INTEGER,
            raceId INTEGER,
            driverId INTEGER,
            constructorId INTEGER,
            number INTEGER,
            grid INTEGER,
            position VARCHAR,
            positionText VARCHAR,
            positionOrder VARCHAR,
            points VARCHAR,
            laps VARCHAR,
            time VARCHAR,
            milliseconds VARCHAR,
            fastestLap VARCHAR,
            rank INTEGER,
            fastestLapTime VARCHAR,
            fastestLapSpeed VARCHAR,
            statusId VARCHAR;